# Generated by Django 4.2.19 on 2025-02-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.livro')),
            ],
        ),
    ]
